<Project Sdk="Microsoft.NET.Sdk">

  

  <ItemGroup>
    <PackageReference Include="coverlet.collector"  />
    <PackageReference Include="Microsoft.NET.Test.Sdk"  />
	  
    <PackageReference Include="xunit.runner.visualstudio"  />
  </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MecanichShop.Tests.Common\MecanichShop.Tests.Common.csproj" />
	</ItemGroup>

</Project>
